# frozen_string_literal: true

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_check_update = false

  nodes = {
    "cp" => { ip: "192.168.56.10", cpus: 2, memory: 2048 },
    "w1" => { ip: "192.168.56.11", cpus: 1, memory: 1536 },
    "w2" => { ip: "192.168.56.12", cpus: 1, memory: 1536 }
  }

  nodes.each do |name, opts|
    config.vm.define name do |n|
      n.vm.hostname = name
      n.vm.network "private_network", ip: opts[:ip]
      n.vm.provider "virtualbox" do |vb|
        vb.name = "kuber-bootstrap-#{name}"
        vb.memory = opts[:memory]
        vb.cpus = opts[:cpus]
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      end
    end
  end
end
