apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-ci
  labels:
    app: hello-ci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-ci
  template:
    metadata:
      labels:
        app: hello-ci
    spec:
      imagePullSecrets:
        - name: gitlab-reg
      containers:
        - name: app
          image: ${IMAGE}
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-ci
spec:
  selector:
    app: hello-ci
  ports:
    - port: 80
      targetPort: 8080
