---
all:
  hosts:
    ch-01:
      ansible_host: 192.168.60.10
      keeper_id: 1
      clickhouse_shard: "01"
      clickhouse_replica: ch-01
    ch-02:
      ansible_host: 192.168.60.11
      keeper_id: 2
      clickhouse_shard: "01"
      clickhouse_replica: ch-02
    ch-03:
      ansible_host: 192.168.60.12
      keeper_id: 3
      clickhouse_shard: "01"
      clickhouse_replica: ch-03
  children:
    clickhouse:
      hosts:
        ch-01:
        ch-02:
        ch-03:
    clickhouse_keeper:
      hosts:
        ch-01:
        ch-02:
        ch-03:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
    ansible_become: true
