import type {SceneScript} from "../../../../shared/types";
import type {TerraformVisual} from "../../templates/createTerraformReel";

export const TOPIC_TITLE = "IAM roles";

export const AUDIO_SRC = "audio/terraform/065-iam-role-policy-attachments.mp3";
/** Fallback if metadata cannot be read; calculateMetadata overrides this. */
export const AUDIO_DURATION_SECONDS = 70.68;

export const HIGHLIGHT_WORDS = [
  "IAM",
  "roles",
] as const;

export const VISUAL: TerraformVisual = {
  mark: "IAM",
  chips: [
    "trust",
    "policy",
    "attach",
  ],
  lines: [
    "role -> policy -> actions",
  ],
  bad: "Admin attach",
  good: "Narrow policy",
  stamp: "LEAST PRIVILEGE",
};

export const SCENE_SCRIPTS: SceneScript[] = [
  { id: "question", text: "A role says who can assume. A policy says what they can do." },
  { id: "explain", text: "In AWS IAM, a role has a trust policy that defines which principals may assume it. Permission policies define allowed actions on resources. Terraform can manage roles and attach managed or inline policies, making identity relationships reviewable alongside infrastructure." },
  { id: "detail", text: "Model trust and permissions separately. Prefer narrowly scoped reusable managed policies when several roles need the same permission set, and attach them deliberately. Use policy documents generated by Terraform data sources where helpful, then inspect the final JSON and test access paths." },
  { id: "pitfall", text: "Attaching an administrator policy for convenience defeats role design and is hard to unwind. Multiple policy attachments can combine unexpectedly. Avoid managing the same attachment through different Terraform resources or manual console changes, because ownership will become confused." },
  { id: "rule", text: "Separate trust from permission and grant only required actions." },
  { id: "cta", text: "Master Terraform faster. Theory, hands-on labs, and interview questions - link in bio." },
];
