apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: lab-tshoot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: nginxx:1.27
          ports:
            - containerPort: 80
