---
all:
  hosts:
    node-01:
      ansible_host: 192.168.56.10
    node-02:
      ansible_host: 192.168.56.11
    node-03:
      ansible_host: 192.168.56.12
  children:
    k8s_cp:
      hosts:
        node-01:
    k8s_workers:
      hosts:
        node-02:
        node-03:
    k8s:
      children:
        k8s_cp:
        k8s_workers:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
    kubeconfig_local: "{{ lookup('env', 'HOME') }}/.kube/nimbus-ops.conf"
