[master]
pg-01 ansible_host=192.168.58.10

[replica]
pg-02 ansible_host=192.168.58.11
pg-03 ansible_host=192.168.58.12

[postgres_cluster:children]
master
replica

[etcd_cluster]
pg-01 ansible_host=192.168.58.10
pg-02 ansible_host=192.168.58.11
pg-03 ansible_host=192.168.58.12

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args=-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
